import { Lesson } from '../../types/lesson';

// 新概念英语第一册完整真实内容
export const realLessons: Lesson[] = [
  // ========== Lesson 1: Excuse me! ==========
  {
    id: 1,
    title: 'Lesson 1: Excuse me!',
    type: 'new',
    grammar: '一般现在时',
    tense: 'Simple Present Tense',
    content: {
      vocabulary: [
        { word: 'excuse', phonetic: '/ɪkˈskjuːz/', meaning: '原谅', examples: ['Excuse me.', 'Excuse me, can you help me?'] },
        { word: 'me', phonetic: '/miː/', meaning: '我（宾格）', examples: ['Tell me.', 'Help me.'] },
        { word: 'yes', phonetic: '/jes/', meaning: '是的', examples: ['Yes, it is.', 'Yes, I can.'] },
        { word: 'is', phonetic: '/ɪz/', meaning: '是（be动词）', examples: ['This is a book.', 'It is mine.'] },
        { word: 'this', phonetic: '/ðɪs/', meaning: '这', examples: ['This is my book.', 'Is this yours?'] },
        { word: 'your', phonetic: '/jɔː/', meaning: '你的，你们的', examples: ['Is this your book?', 'Your name is Tom.'] },
        { word: 'handbag', phonetic: '/ˈhændbæɡ/', meaning: '手提包', examples: ['Is this your handbag?', 'A nice handbag.'] },
        { word: 'pardon', phonetic: '/ˈpɑːdn/', meaning: '原谅，请再说一遍', examples: ['I beg your pardon.', 'Pardon?'] },
        { word: 'it', phonetic: '/ɪt/', meaning: '它', examples: ['It is a cat.', 'Is it yours?'] },
        { word: 'thank you', phonetic: '/θæŋk juː/', meaning: '谢谢你', examples: ['Thank you very much.', 'Thank you for your help.'] },
        { word: 'very much', phonetic: '/ˈveri mʌtʃ/', meaning: '非常', examples: ['Thank you very much.', 'I like it very much.'] },
      ],
      sentences: [
        { english: 'Excuse me!', chinese: '对不起！', grammarPoints: ['日常用语', '引起注意'] },
        { english: 'Yes?', chinese: '什么事？', grammarPoints: ['日常用语', '询问'] },
        { english: 'Is this your handbag?', chinese: '这是您的手提包吗？', grammarPoints: ['一般疑问句', 'be动词'] },
        { english: 'Pardon?', chinese: '请再说一遍。', grammarPoints: ['日常用语', '请求重复'] },
        { english: 'Yes, it is.', chinese: '是的，是我的。', grammarPoints: ['肯定回答', 'be动词'] },
        { english: 'Thank you very much.', chinese: '非常感谢。', grammarPoints: ['日常用语', '表示感谢'] },
      ],
      text: {
        title: 'Excuse me!',
        paragraphs: [
          { speaker: 'A', content: 'Excuse me!' },
          { speaker: 'B', content: 'Yes?' },
          { speaker: 'A', content: 'Is this your handbag?' },
          { speaker: 'B', content: 'Pardon?' },
          { speaker: 'A', content: 'Is this your handbag?' },
          { speaker: 'B', content: 'Yes, it is.' },
          { speaker: 'B', content: 'Thank you very much.' },
        ],
        translation: ['对不起！', '什么事？', '这是您的手提包吗？', '请再说一遍。', '这是您的手提包吗？', '是的，是我的。', '非常感谢。'],
      },
      exercises: [
        { type: 'listening', content: { question: '听录音，选择正确答案：Excuse me! 的意思是？', options: ['打扰一下', '谢谢你', '对不起', '再见'] }, answer: '打扰一下', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Is this your handbag?', sentence: 'Is this your handbag?' }, answer: 'Is this your handbag?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：Thank you very much.', sentence: 'Thank you very much.' }, answer: '非常感谢。', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：excuse', word: 'excuse', hint: '/ɪkˈskjuːz/' }, answer: 'excuse', score: 10 },
      ],
    },
  },
  // ========== Lesson 2: Is this your...? ==========
  {
    id: 2,
    title: 'Lesson 2: Is this your...?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'pen', phonetic: '/pen/', meaning: '钢笔', examples: ['This is my pen.', 'Is this your pen?'] },
        { word: 'pencil', phonetic: '/ˈpensl/', meaning: '铅笔', examples: ['I have a pencil.', 'Is this your pencil?'] },
        { word: 'book', phonetic: '/bʊk/', meaning: '书', examples: ['This is my book.', 'Is this your book?'] },
        { word: 'watch', phonetic: '/wɒtʃ/', meaning: '手表', examples: ['This is my watch.', 'Is this your watch?'] },
        { word: 'coat', phonetic: '/kəʊt/', meaning: '大衣', examples: ['This is my coat.', 'Is this your coat?'] },
        { word: 'dress', phonetic: '/dres/', meaning: '连衣裙', examples: ['This is my dress.', 'Is this your dress?'] },
        { word: 'skirt', phonetic: '/skɜːt/', meaning: '裙子', examples: ['This is my skirt.', 'Is this your skirt?'] },
        { word: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫', examples: ['This is my shirt.', 'Is this your shirt?'] },
      ],
      sentences: [
        { english: 'Is this your pen?', chinese: '这是你的钢笔吗？', grammarPoints: ['一般疑问句'] },
        { english: 'Yes, it is.', chinese: '是的，是我的。', grammarPoints: ['肯定回答'] },
        { english: 'Is this your pencil?', chinese: '这是你的铅笔吗？', grammarPoints: ['一般疑问句'] },
        { english: 'No, it is not.', chinese: '不，不是。', grammarPoints: ['否定回答'] },
      ],
      text: {
        title: 'Is this your...?',
        paragraphs: [
          { speaker: 'A', content: 'Is this your pen?' },
          { speaker: 'B', content: 'Yes, it is.' },
          { speaker: 'A', content: 'Is this your pencil?' },
          { speaker: 'B', content: 'No, it is not.' },
          { speaker: 'A', content: 'Is this your book?' },
          { speaker: 'B', content: 'Yes, it is.' },
        ],
        translation: ['这是你的钢笔吗？', '是的，是我的。', '这是你的铅笔吗？', '不，不是。', '这是你的书吗？', '是的，是我的。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Is this your watch? 的正确回答是？', options: ['Yes, it is.', 'Yes, I am.', 'Yes, this is.', 'Yes, he is.'] }, answer: 'Yes, it is.', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Is this your coat?', sentence: 'Is this your coat?' }, answer: 'Is this your coat?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：这是你的衬衫吗？', sentence: 'Is this your shirt?' }, answer: 'Is this your shirt?', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：book', word: 'book', hint: '/bʊk/' }, answer: 'book', score: 10 },
      ],
    },
  },
  // ========== Lesson 3: Sorry, sir. ==========
  {
    id: 3,
    title: 'Lesson 3: Sorry, sir.',
    type: 'new',
    grammar: '否定句',
    content: {
      vocabulary: [
        { word: 'sorry', phonetic: '/ˈsɒri/', meaning: '对不起的', examples: ['I am sorry.', 'Sorry, sir.'] },
        { word: 'sir', phonetic: '/sɜː/', meaning: '先生', examples: ['Sorry, sir.', 'Yes, sir.'] },
        { word: 'not', phonetic: '/nɒt/', meaning: '不', examples: ['This is not my ticket.', 'It is not mine.'] },
        { word: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '伞', examples: ['My umbrella is black.', 'This is my umbrella.'] },
        { word: 'ticket', phonetic: '/ˈtɪkɪt/', meaning: '票', examples: ['Here is my ticket.', 'This is your ticket.'] },
        { word: 'number', phonetic: '/ˈnʌmbə/', meaning: '号码', examples: ['Number five.', 'What is your number?'] },
        { word: 'five', phonetic: '/faɪv/', meaning: '五', examples: ['Five books.', 'I have five pens.'] },
      ],
      sentences: [
        { english: 'Sorry, sir.', chinese: '对不起，先生。', grammarPoints: ['道歉'] },
        { english: 'This is not my ticket.', chinese: '这不是我的票。', grammarPoints: ['否定句'] },
        { english: 'Is this your umbrella?', chinese: '这是你的伞吗？', grammarPoints: ['一般疑问句'] },
        { english: 'No, it is not.', chinese: '不，不是。', grammarPoints: ['否定回答'] },
      ],
      text: {
        title: 'Sorry, sir.',
        paragraphs: [
          { speaker: 'A', content: 'My coat and my umbrella please.' },
          { speaker: 'B', content: 'Here is your ticket.' },
          { speaker: 'A', content: 'Thank you, sir.' },
          { speaker: 'B', content: 'Number five.' },
          { speaker: 'B', content: "Here's your umbrella and your coat." },
          { speaker: 'A', content: 'This is not my umbrella.' },
          { speaker: 'B', content: 'Sorry, sir.' },
          { speaker: 'B', content: 'Is this your umbrella?' },
          { speaker: 'A', content: 'No, it is not.' },
          { speaker: 'B', content: 'Is this it?' },
          { speaker: 'A', content: 'Yes, it is.' },
          { speaker: 'A', content: 'Thank you very much.' },
        ],
        translation: ['请把我的大衣和伞拿给我。', '这是您的票。', '谢谢，先生。', '是5号。', '这是您的伞和大衣。', '这不是我的伞。', '对不起，先生。', '这把伞是您的吗？', '不，不是！', '这把是吗？', '是，是这把。', '非常感谢。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'This is not my umbrella. 的意思是？', options: ['这是我的伞', '这不是我的伞', '这是你的伞', '这不是你的伞'] }, answer: '这不是我的伞', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Sorry, sir.', sentence: 'Sorry, sir.' }, answer: 'Sorry, sir.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：Number five.', sentence: 'Number five.' }, answer: '5号。', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：umbrella', word: 'umbrella', hint: '/ʌmˈbrelə/' }, answer: 'umbrella', score: 10 },
      ],
    },
  },
  // ========== Lesson 4: Is this your...? ==========
  {
    id: 4,
    title: 'Lesson 4: Is this your...?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'suit', phonetic: '/suːt/', meaning: '一套衣服', examples: ['This is my suit.', 'Is this your suit?'] },
        { word: 'school', phonetic: '/skuːl/', meaning: '学校', examples: ['I go to school.', 'This is my school.'] },
        { word: 'teacher', phonetic: '/ˈtiːtʃə/', meaning: '老师', examples: ['My teacher is nice.', 'This is my teacher.'] },
        { word: 'son', phonetic: '/sʌn/', meaning: '儿子', examples: ['This is my son.', 'He is my son.'] },
        { word: 'daughter', phonetic: '/ˈdɔːtə/', meaning: '女儿', examples: ['This is my daughter.', 'She is my daughter.'] },
      ],
      sentences: [
        { english: 'Is this your suit?', chinese: '这是你的衣服吗？', grammarPoints: ['一般疑问句'] },
        { english: 'Yes, it is.', chinese: '是的，是我的。', grammarPoints: ['肯定回答'] },
        { english: 'Is this your school?', chinese: '这是你的学校吗？', grammarPoints: ['一般疑问句'] },
        { english: 'No, it is not.', chinese: '不，不是。', grammarPoints: ['否定回答'] },
      ],
      text: {
        title: 'Is this your...?',
        paragraphs: [
          { speaker: 'A', content: 'Is this your suit?' },
          { speaker: 'B', content: 'Yes, it is.' },
          { speaker: 'A', content: 'Is this your school?' },
          { speaker: 'B', content: 'No, it is not.' },
          { speaker: 'A', content: 'Is this your teacher?' },
          { speaker: 'B', content: 'Yes, it is.' },
        ],
        translation: ['这是你的衣服吗？', '是的，是我的。', '这是你的学校吗？', '不，不是。', '这是你的老师吗？', '是的，是我的。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Is this your son? 的正确回答是？', options: ['Yes, he is.', 'Yes, it is.', 'Yes, this is.', 'Yes, I am.'] }, answer: 'Yes, it is.', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Is this your daughter?', sentence: 'Is this your daughter?' }, answer: 'Is this your daughter?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：这是你的学校吗？', sentence: 'Is this your school?' }, answer: 'Is this your school?', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：school', word: 'school', hint: '/skuːl/' }, answer: 'school', score: 10 },
      ],
    },
  },
  // ========== Lesson 5: Nice to meet you. ==========
  {
    id: 5,
    title: 'Lesson 5: Nice to meet you.',
    type: 'new',
    grammar: '介绍与问候',
    content: {
      vocabulary: [
        { word: 'good', phonetic: '/ɡʊd/', meaning: '好的', examples: ['Good morning.', 'Good afternoon.'] },
        { word: 'morning', phonetic: '/ˈmɔːnɪŋ/', meaning: '早晨', examples: ['Good morning.', 'In the morning.'] },
        { word: 'Mr.', phonetic: '/ˈmɪstə/', meaning: '先生', examples: ['Mr. Blake.', 'Good morning, Mr. Blake.'] },
        { word: 'Miss', phonetic: '/mɪs/', meaning: '小姐', examples: ['Miss Sophie.', 'This is Miss Sophie.'] },
        { word: 'student', phonetic: '/ˈstjuːdnt/', meaning: '学生', examples: ['She is a student.', 'I am a student.'] },
        { word: 'French', phonetic: '/frentʃ/', meaning: '法国的', examples: ['She is French.', 'French food.'] },
        { word: 'German', phonetic: '/ˈdʒɜːmən/', meaning: '德国的', examples: ['He is German.', 'German cars.'] },
        { word: 'Japanese', phonetic: '/ˌdʒæpəˈniːz/', meaning: '日本的', examples: ['She is Japanese.', 'Japanese food.'] },
        { word: 'Korean', phonetic: '/kəˈriːən/', meaning: '韩国的', examples: ['He is Korean.', 'Korean food.'] },
        { word: 'Chinese', phonetic: '/ˌtʃaɪˈniːz/', meaning: '中国的', examples: ['He is Chinese.', 'Chinese food.'] },
        { word: 'nice', phonetic: '/naɪs/', meaning: '好的', examples: ['Nice to meet you.', 'Nice day.'] },
        { word: 'meet', phonetic: '/miːt/', meaning: '遇见', examples: ['Nice to meet you.', 'Meet my friend.'] },
      ],
      sentences: [
        { english: 'Good morning.', chinese: '早上好。', grammarPoints: ['问候语'] },
        { english: 'Good morning, Mr. Blake.', chinese: '早上好，布莱克先生。', grammarPoints: ['问候语', '称呼'] },
        { english: 'This is Miss Sophie Dupont.', chinese: '这位是索菲娅·杜邦小姐。', grammarPoints: ['介绍'] },
        { english: 'Sophie is a new student.', chinese: '索菲娅是个新学生。', grammarPoints: ['介绍'] },
        { english: 'She is French.', chinese: '她是法国人。', grammarPoints: ['国籍'] },
        { english: 'Nice to meet you.', chinese: '很高兴见到你。', grammarPoints: ['问候语'] },
      ],
      text: {
        title: 'Nice to meet you.',
        paragraphs: [
          { speaker: 'Mr. Blake', content: 'Good morning.' },
          { speaker: 'Students', content: 'Good morning, Mr. Blake.' },
          { speaker: 'Mr. Blake', content: 'This is Miss Sophie Dupont.' },
          { speaker: 'Mr. Blake', content: 'Sophie is a new student.' },
          { speaker: 'Mr. Blake', content: 'She is French.' },
          { speaker: 'Mr. Blake', content: 'Sophie, this is Hans.' },
          { speaker: 'Mr. Blake', content: 'He is German.' },
          { speaker: 'Hans', content: 'Nice to meet you.' },
          { speaker: 'Mr. Blake', content: 'And this is Naoko.' },
          { speaker: 'Mr. Blake', content: "She's Japanese." },
          { speaker: 'Naoko', content: 'Nice to meet you.' },
          { speaker: 'Mr. Blake', content: 'And this is Chang-woo.' },
          { speaker: 'Mr. Blake', content: "He's Korean." },
          { speaker: 'Chang-woo', content: 'Nice to meet you.' },
          { speaker: 'Mr. Blake', content: 'And this is Luming.' },
          { speaker: 'Mr. Blake', content: 'He is Chinese.' },
          { speaker: 'Luming', content: 'Nice to meet you.' },
          { speaker: 'Mr. Blake', content: 'And this is Xiaohui.' },
          { speaker: 'Mr. Blake', content: "She's Chinese, too." },
          { speaker: 'Xiaohui', content: 'Nice to meet you.' },
        ],
        translation: ['早上好。', '早上好，布莱克先生。', '这位是索菲娅·杜邦小姐。', '索菲娅是个新学生。', '她是法国人。', '索菲娅，这位是汉斯。', '他是德国人。', '很高兴见到你。', '这位是直子。', '她是日本人。', '很高兴见到你。', '这位是昌宇。', '他是韩国人。', '很高兴见到你。', '这位是鲁明。', '他是中国人。', '很高兴见到你。', '这位是晓惠。', '她也是中国人。', '很高兴见到你。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'She is French. 的意思是？', options: ['她是法国人', '她是德国人', '她是日本人', '她是中国人'] }, answer: '她是法国人', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Nice to meet you.', sentence: 'Nice to meet you.' }, answer: 'Nice to meet you.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：Good morning.', sentence: 'Good morning.' }, answer: '早上好。', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：student', word: 'student', hint: '/ˈstjuːdnt/' }, answer: 'student', score: 10 },
      ],
    },
  },
  // ========== Lesson 6: What make is it? ==========
  {
    id: 6,
    title: 'Lesson 6: What make is it?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'make', phonetic: '/meɪk/', meaning: '牌子', examples: ['What make is it?', 'It is a Toyota.'] },
        { word: 'car', phonetic: '/kɑː/', meaning: '汽车', examples: ['This is my car.', 'What make is your car?'] },
        { word: 'Ford', phonetic: '/fɔːd/', meaning: '福特', examples: ['It is a Ford.', 'Ford car.'] },
        { word: 'Mercedes', phonetic: '/mɜːˈsiːdɪz/', meaning: '奔驰', examples: ['It is a Mercedes.', 'Mercedes car.'] },
        { word: 'Peugeot', phonetic: '/ˈpɜːʒeɪ/', meaning: '标致', examples: ['It is a Peugeot.', 'Peugeot car.'] },
        { word: 'Volvo', phonetic: '/ˈvɒlvəʊ/', meaning: '沃尔沃', examples: ['It is a Volvo.', 'Volvo car.'] },
        { word: 'Mini', phonetic: '/ˈmɪni/', meaning: '迷你', examples: ['It is a Mini.', 'Mini car.'] },
        { word: 'Toyota', phonetic: '/tɔɪˈəʊtə/', meaning: '丰田', examples: ['It is a Toyota.', 'Toyota car.'] },
      ],
      sentences: [
        { english: 'What make is it?', chinese: '它是什么牌子的？', grammarPoints: ['特殊疑问句'] },
        { english: "It's a Ford.", chinese: '它是福特牌的。', grammarPoints: ['回答'] },
        { english: 'What make is your car?', chinese: '你的汽车是什么牌子的？', grammarPoints: ['特殊疑问句'] },
        { english: "It's a Toyota.", chinese: '它是丰田牌的。', grammarPoints: ['回答'] },
      ],
      text: {
        title: 'What make is it?',
        paragraphs: [
          { speaker: 'A', content: 'What make is it?' },
          { speaker: 'B', content: "It's a Ford." },
          { speaker: 'A', content: 'What make is your car?' },
          { speaker: 'B', content: "It's a Toyota." },
          { speaker: 'A', content: 'What make is this car?' },
          { speaker: 'B', content: "It's a Mercedes." },
        ],
        translation: ['它是什么牌子的？', '它是福特牌的。', '你的汽车是什么牌子的？', '它是丰田牌的。', '这辆车是什么牌子的？', '它是奔驰牌的。'],
      },
      exercises: [
        { type: 'listening', content: { question: "It's a Volvo. 的意思是？", options: ['它是沃尔沃', '它是宝马', '它是丰田', '它是福特'] }, answer: '它是沃尔沃', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What make is it?', sentence: 'What make is it?' }, answer: 'What make is it?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：它是宝马。', sentence: "It's a BMW." }, answer: "It's a BMW.", score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：car', word: 'car', hint: '/kɑː/' }, answer: 'car', score: 10 },
      ],
    },
  },
  // ========== Lesson 7: Are you a teacher? ==========
  {
    id: 7,
    title: 'Lesson 7: Are you a teacher?',
    type: 'new',
    grammar: '职业与国籍',
    content: {
      vocabulary: [
        { word: 'I', phonetic: '/aɪ/', meaning: '我', examples: ['I am a student.', 'I like English.'] },
        { word: 'am', phonetic: '/æm/', meaning: '是（be动词）', examples: ['I am a student.', 'I am happy.'] },
        { word: 'name', phonetic: '/neɪm/', meaning: '名字', examples: ['My name is Robert.', 'What is your name?'] },
        { word: 'Robert', phonetic: '/ˈrɒbət/', meaning: '罗伯特', examples: ['My name is Robert.', 'Robert is my friend.'] },
        { word: 'Sophie', phonetic: '/ˈsəʊfi/', meaning: '索菲娅', examples: ['My name is Sophie.', 'Sophie is my friend.'] },
        { word: 'French', phonetic: '/frentʃ/', meaning: '法国的', examples: ['I am French.', 'She is French.'] },
        { word: 'Italian', phonetic: '/ɪˈtæliən/', meaning: '意大利的', examples: ['I am Italian.', 'He is Italian.'] },
        { word: 'teacher', phonetic: '/ˈtiːtʃə/', meaning: '教师', examples: ['Are you a teacher?', 'I am a teacher.'] },
        { word: 'job', phonetic: '/dʒɒb/', meaning: '工作', examples: ['What is your job?', 'My job is engineer.'] },
        { word: 'keyboard', phonetic: '/ˈkiːbɔːd/', meaning: '键盘', examples: ['Keyboard operator.', 'Computer keyboard.'] },
        { word: 'operator', phonetic: '/ˈɒpəreɪtə/', meaning: '操作员', examples: ['Keyboard operator.', 'Machine operator.'] },
        { word: 'engineer', phonetic: '/ˌendʒɪˈnɪə/', meaning: '工程师', examples: ['I am an engineer.', 'He is an engineer.'] },
      ],
      sentences: [
        { english: 'I am a new student.', chinese: '我是个新学生。', grammarPoints: ['自我介绍'] },
        { english: 'My name is Robert.', chinese: '我的名字叫罗伯特。', grammarPoints: ['介绍名字'] },
        { english: 'Nice to meet you.', chinese: '很高兴见到你。', grammarPoints: ['问候语'] },
        { english: 'Are you French?', chinese: '你是法国人吗？', grammarPoints: ['一般疑问句', '国籍'] },
        { english: 'Yes, I am.', chinese: '是的，我是。', grammarPoints: ['肯定回答'] },
        { english: 'Are you French too?', chinese: '你也是法国人吗？', grammarPoints: ['一般疑问句'] },
        { english: 'No, I am not.', chinese: '不，我不是。', grammarPoints: ['否定回答'] },
        { english: 'What nationality are you?', chinese: '你是哪国人？', grammarPoints: ['特殊疑问句', '国籍'] },
        { english: 'I am Italian.', chinese: '我是意大利人。', grammarPoints: ['回答国籍'] },
        { english: 'Are you a teacher?', chinese: '你是教师吗？', grammarPoints: ['一般疑问句', '职业'] },
        { english: 'No, I am not.', chinese: '不，我不是。', grammarPoints: ['否定回答'] },
        { english: "What's your job?", chinese: '你是做什么工作的？', grammarPoints: ['特殊疑问句', '职业'] },
        { english: 'I am a keyboard operator.', chinese: '我是电脑录入员。', grammarPoints: ['回答职业'] },
        { english: 'I am an engineer.', chinese: '我是工程师。', grammarPoints: ['回答职业'] },
      ],
      text: {
        title: 'Are you a teacher?',
        paragraphs: [
          { speaker: 'Robert', content: 'I am a new student.' },
          { speaker: 'Robert', content: 'My name is Robert.' },
          { speaker: 'Sophie', content: 'Nice to meet you.' },
          { speaker: 'Sophie', content: 'My name is Sophie.' },
          { speaker: 'Sophie', content: 'Are you French?' },
          { speaker: 'Robert', content: 'Yes, I am.' },
          { speaker: 'Sophie', content: 'Are you French too?' },
          { speaker: 'Robert', content: 'No, I am not.' },
          { speaker: 'Sophie', content: 'What nationality are you?' },
          { speaker: 'Robert', content: 'I am Italian.' },
          { speaker: 'Sophie', content: 'Are you a teacher?' },
          { speaker: 'Robert', content: 'No, I am not.' },
          { speaker: 'Sophie', content: "What's your job?" },
          { speaker: 'Robert', content: 'I am a keyboard operator.' },
          { speaker: 'Robert', content: "What's your job?" },
          { speaker: 'Sophie', content: 'I am an engineer.' },
        ],
        translation: ['我是个新学生。', '我的名字叫罗伯特。', '很高兴见到你。', '我的名字叫索菲娅。', '你是法国人吗？', '是的，我是。', '你也是法国人吗？', '不，我不是。', '你是哪国人？', '我是意大利人。', '你是教师吗？', '不，我不是。', '你是做什么工作的？', '我是电脑录入员。', '你是做什么工作的？', '我是工程师。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Are you a teacher? 的否定回答是？', options: ['No, I am not.', 'No, it is not.', 'No, you are not.', 'No, he is not.'] }, answer: 'No, I am not.', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What is your job?', sentence: 'What is your job?' }, answer: 'What is your job?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：我是工程师。', sentence: 'I am an engineer.' }, answer: 'I am an engineer.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：teacher', word: 'teacher', hint: '/ˈtiːtʃə/' }, answer: 'teacher', score: 10 },
      ],
    },
  },
  // ========== Lesson 8: What's your job? ==========
  {
    id: 8,
    title: 'Lesson 8: What\'s your job?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'policeman', phonetic: '/pəˈliːsmən/', meaning: '警察', examples: ['He is a policeman.', 'I am a policeman.'] },
        { word: 'policewoman', phonetic: '/pəˈliːswʊmən/', meaning: '女警察', examples: ['She is a policewoman.', 'I am a policewoman.'] },
        { word: 'taxi driver', phonetic: '/ˈtæksi ˈdraɪvə/', meaning: '出租车司机', examples: ['He is a taxi driver.', 'I am a taxi driver.'] },
        { word: 'air hostess', phonetic: '/ˈeə ˈhəʊstɪs/', meaning: '空中小姐', examples: ['She is an air hostess.', 'I am an air hostess.'] },
        { word: 'postman', phonetic: '/ˈpəʊstmən/', meaning: '邮递员', examples: ['He is a postman.', 'I am a postman.'] },
        { word: 'nurse', phonetic: '/nɜːs/', meaning: '护士', examples: ['She is a nurse.', 'I am a nurse.'] },
        { word: 'mechanic', phonetic: '/mɪˈkænɪk/', meaning: '机械师', examples: ['He is a mechanic.', 'I am a mechanic.'] },
        { word: 'hairdresser', phonetic: '/ˈheədresə/', meaning: '理发师', examples: ['He is a hairdresser.', 'I am a hairdresser.'] },
        { word: 'housewife', phonetic: '/ˈhaʊswaɪf/', meaning: '家庭主妇', examples: ['She is a housewife.', 'I am a housewife.'] },
        { word: 'milkman', phonetic: '/ˈmɪlkmən/', meaning: '送奶工', examples: ['He is a milkman.', 'I am a milkman.'] },
      ],
      sentences: [
        { english: "What's your job?", chinese: '你是做什么工作的？', grammarPoints: ['特殊疑问句', '职业'] },
        { english: 'I am a policeman.', chinese: '我是警察。', grammarPoints: ['回答职业'] },
        { english: 'I am a policewoman.', chinese: '我是女警察。', grammarPoints: ['回答职业'] },
        { english: 'I am a taxi driver.', chinese: '我是出租车司机。', grammarPoints: ['回答职业'] },
        { english: 'I am an air hostess.', chinese: '我是空中小姐。', grammarPoints: ['回答职业'] },
      ],
      text: {
        title: "What's your job?",
        paragraphs: [
          { speaker: 'A', content: "What's your job?" },
          { speaker: 'B', content: 'I am a policeman.' },
          { speaker: 'A', content: "What's your job?" },
          { speaker: 'C', content: 'I am a policewoman.' },
          { speaker: 'A', content: "What's your job?" },
          { speaker: 'D', content: 'I am a taxi driver.' },
          { speaker: 'A', content: "What's your job?" },
          { speaker: 'E', content: 'I am an air hostess.' },
        ],
        translation: ['你是做什么工作的？', '我是警察。', '你是做什么工作的？', '我是女警察。', '你是做什么工作的？', '我是出租车司机。', '你是做什么工作的？', '我是空中小姐。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'I am a nurse. 的意思是？', options: ['我是护士', '我是医生', '我是警察', '我是老师'] }, answer: '我是护士', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What is your job?', sentence: 'What is your job?' }, answer: 'What is your job?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：我是家庭主妇。', sentence: 'I am a housewife.' }, answer: 'I am a housewife.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：nurse', word: 'nurse', hint: '/nɜːs/' }, answer: 'nurse', score: 10 },
      ],
    },
  },
  // ========== Lesson 9: How are you today? ==========
  {
    id: 9,
    title: 'Lesson 9: How are you today?',
    type: 'new',
    grammar: '健康状况询问',
    content: {
      vocabulary: [
        { word: 'hello', phonetic: '/həˈləʊ/', meaning: '你好', examples: ['Hello, Helen.', 'Hello, how are you?'] },
        { word: 'hi', phonetic: '/haɪ/', meaning: '嗨', examples: ['Hi, Steven.', 'Hi, how are you?'] },
        { word: 'how', phonetic: '/haʊ/', meaning: '怎样', examples: ['How are you?', 'How is he?'] },
        { word: 'today', phonetic: '/təˈdeɪ/', meaning: '今天', examples: ['How are you today?', 'Today is Monday.'] },
        { word: 'well', phonetic: '/wel/', meaning: '好', examples: ['I am very well.', 'He is well.'] },
        { word: 'fine', phonetic: '/faɪn/', meaning: '好', examples: ['I am fine.', 'She is fine.'] },
        { word: 'thanks', phonetic: '/θæŋks/', meaning: '谢谢', examples: ['I am fine, thanks.', 'Thanks for your help.'] },
        { word: 'goodbye', phonetic: '/ˌɡʊdˈbaɪ/', meaning: '再见', examples: ['Goodbye, Helen.', 'Goodbye, see you tomorrow.'] },
        { word: 'nice', phonetic: '/naɪs/', meaning: '愉快的', examples: ['Nice to see you.', 'Nice day.'] },
        { word: 'see', phonetic: '/siː/', meaning: '看见', examples: ['Nice to see you.', 'See you tomorrow.'] },
      ],
      sentences: [
        { english: 'Hello, Helen.', chinese: '你好，海伦。', grammarPoints: ['问候语'] },
        { english: 'Hi, Steven.', chinese: '你好，史蒂文。', grammarPoints: ['问候语'] },
        { english: 'How are you today?', chinese: '你今天好吗？', grammarPoints: ['健康状况询问'] },
        { english: 'I am very well, thank you.', chinese: '很好，谢谢你。', grammarPoints: ['回答健康状况'] },
        { english: 'And you?', chinese: '你好吗？', grammarPoints: ['反问'] },
        { english: 'I am fine, thanks.', chinese: '很好，谢谢。', grammarPoints: ['回答健康状况'] },
        { english: 'How is Tony?', chinese: '托尼好吗？', grammarPoints: ['询问他人健康'] },
        { english: 'He is fine, thanks.', chinese: '他很好，谢谢。', grammarPoints: ['回答他人健康'] },
        { english: 'Goodbye, Helen.', chinese: '再见，海伦。', grammarPoints: ['告别'] },
        { english: 'Nice to see you.', chinese: '见到你真高兴。', grammarPoints: ['告别语'] },
        { english: 'Nice to see you, too.', chinese: '我见到你也很高兴。', grammarPoints: ['回应告别语'] },
      ],
      text: {
        title: 'How are you today?',
        paragraphs: [
          { speaker: 'Steven', content: 'Hello, Helen.' },
          { speaker: 'Helen', content: 'Hi, Steven.' },
          { speaker: 'Steven', content: 'How are you today?' },
          { speaker: 'Helen', content: 'I am very well, thank you.' },
          { speaker: 'Helen', content: 'And you?' },
          { speaker: 'Steven', content: 'I am fine, thanks.' },
          { speaker: 'Steven', content: 'How is Tony?' },
          { speaker: 'Helen', content: 'He is fine, thanks.' },
          { speaker: 'Steven', content: "How's Emma?" },
          { speaker: 'Helen', content: "She's very well, too, Helen." },
          { speaker: 'Steven', content: 'Goodbye, Helen.' },
          { speaker: 'Helen', content: 'Nice to see you.' },
          { speaker: 'Steven', content: 'Nice to see you, too, Steven.' },
          { speaker: 'Helen', content: 'Goodbye.' },
        ],
        translation: ['你好，海伦。', '你好，史蒂文。', '你今天好吗？', '很好，谢谢你。', '你好吗？', '很好，谢谢。', '托尼好吗？', '他很好，谢谢。', '埃玛好吗？', '她也很好，海伦。', '再见，海伦。', '见到你真高兴。', '我见到你也很高兴，史蒂文。', '再见。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'How are you today? 的意思是？', options: ['你今天好吗？', '你是谁？', '你多大了？', '你叫什么名字？'] }, answer: '你今天好吗？', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：I am very well, thank you.', sentence: 'I am very well, thank you.' }, answer: 'I am very well, thank you.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：Goodbye.', sentence: 'Goodbye.' }, answer: '再见。', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：hello', word: 'hello', hint: '/həˈləʊ/' }, answer: 'hello', score: 10 },
      ],
    },
  },
  // ========== Lesson 10: Look at... ==========
  {
    id: 10,
    title: 'Lesson 10: Look at...',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'look', phonetic: '/lʊk/', meaning: '看', examples: ['Look at that.', 'Look at me.'] },
        { word: 'at', phonetic: '/æt/', meaning: '在', examples: ['Look at that.', 'At home.'] },
        { word: 'fat', phonetic: '/fæt/', meaning: '胖的', examples: ['He is fat.', 'The cat is fat.'] },
        { word: 'thin', phonetic: '/θɪn/', meaning: '瘦的', examples: ['She is thin.', 'The dog is thin.'] },
        { word: 'tall', phonetic: '/tɔːl/', meaning: '高的', examples: ['He is tall.', 'The tree is tall.'] },
        { word: 'short', phonetic: '/ʃɔːt/', meaning: '矮的', examples: ['She is short.', 'The man is short.'] },
        { word: 'dirty', phonetic: '/ˈdɜːti/', meaning: '脏的', examples: ['The shirt is dirty.', 'My hands are dirty.'] },
        { word: 'clean', phonetic: '/kliːn/', meaning: '干净的', examples: ['The shirt is clean.', 'My hands are clean.'] },
        { word: 'hot', phonetic: '/hɒt/', meaning: '热的', examples: ['It is hot.', 'The soup is hot.'] },
        { word: 'cold', phonetic: '/kəʊld/', meaning: '冷的', examples: ['It is cold.', 'The ice is cold.'] },
      ],
      sentences: [
        { english: 'Look at that man.', chinese: '看那个男人。', grammarPoints: ['祈使句'] },
        { english: 'He is fat.', chinese: '他很胖。', grammarPoints: ['描述外貌'] },
        { english: 'Look at that woman.', chinese: '看那个女人。', grammarPoints: ['祈使句'] },
        { english: 'She is thin.', chinese: '她很瘦。', grammarPoints: ['描述外貌'] },
        { english: 'Look at that boy.', chinese: '看那个男孩。', grammarPoints: ['祈使句'] },
        { english: 'He is tall.', chinese: '他很高。', grammarPoints: ['描述外貌'] },
        { english: 'Look at that girl.', chinese: '看那个女孩。', grammarPoints: ['祈使句'] },
        { english: 'She is short.', chinese: '她很矮。', grammarPoints: ['描述外貌'] },
      ],
      text: {
        title: 'Look at...',
        paragraphs: [
          { speaker: 'A', content: 'Look at that man.' },
          { speaker: 'B', content: 'He is fat.' },
          { speaker: 'A', content: 'Look at that woman.' },
          { speaker: 'B', content: 'She is thin.' },
          { speaker: 'A', content: 'Look at that boy.' },
          { speaker: 'B', content: 'He is tall.' },
          { speaker: 'A', content: 'Look at that girl.' },
          { speaker: 'B', content: 'She is short.' },
        ],
        translation: ['看那个男人。', '他很胖。', '看那个女人。', '她很瘦。', '看那个男孩。', '他很高。', '看那个女孩。', '她很矮。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Look at that girl. 的意思是？', options: ['看那个女孩', '看那个男孩', '看那个男人', '看那个女人'] }, answer: '看那个女孩', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Look at that man.', sentence: 'Look at that man.' }, answer: 'Look at that man.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：他很高。', sentence: 'He is tall.' }, answer: 'He is tall.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：tall', word: 'tall', hint: '/tɔːl/' }, answer: 'tall', score: 10 },
      ],
    },
  },
  // ========== Lesson 11: Is this your shirt? ==========
  {
    id: 11,
    title: 'Lesson 11: Is this your shirt?',
    type: 'new',
    grammar: '物主代词',
    content: {
      vocabulary: [
        { word: 'whose', phonetic: '/huːz/', meaning: '谁的', examples: ['Whose shirt is that?', 'Whose bag is this?'] },
        { word: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫', examples: ['This is my shirt.', 'Whose shirt is that?'] },
        { word: 'Dave', phonetic: '/deɪv/', meaning: '戴夫', examples: ['This is Dave.', 'Dave is my friend.'] },
        { word: 'sir', phonetic: '/sɜː/', meaning: '先生', examples: ['Yes, sir.', 'Sorry, sir.'] },
        { word: 'blue', phonetic: '/bluː/', meaning: '蓝色的', examples: ['My shirt is blue.', 'Blue sky.'] },
        { word: 'Tim', phonetic: '/tɪm/', meaning: '蒂姆', examples: ['This is Tim.', 'Tim is my friend.'] },
        { word: 'white', phonetic: '/waɪt/', meaning: '白色的', examples: ['Tim\'s shirt is white.', 'White snow.'] },
        { word: 'perhaps', phonetic: '/pəˈhæps/', meaning: '也许', examples: ['Perhaps it is.', 'Perhaps he is here.'] },
        { word: 'catch', phonetic: '/kætʃ/', meaning: '抓住', examples: ['Catch!', 'Catch the ball.'] },
      ],
      sentences: [
        { english: 'Whose shirt is that?', chinese: '那是谁的衬衫？', grammarPoints: ['特殊疑问句', '物主代词'] },
        { english: 'Is this your shirt, Dave?', chinese: '戴夫，这是你的衬衫吗？', grammarPoints: ['一般疑问句', '物主代词'] },
        { english: 'No, sir.', chinese: '不，先生。', grammarPoints: ['否定回答'] },
        { english: 'It is not my shirt.', chinese: '这不是我的衬衫。', grammarPoints: ['否定句', '物主代词'] },
        { english: 'This is my shirt.', chinese: '这是我的衬衫。', grammarPoints: ['肯定句', '物主代词'] },
        { english: 'My shirt is blue.', chinese: '我的衬衫是蓝色的。', grammarPoints: ['描述', '物主代词'] },
        { english: 'Is this shirt Tim\'s?', chinese: '这件衬衫是蒂姆的吗？', grammarPoints: ['所有格'] },
        { english: 'Perhaps it is, sir.', chinese: '也许是，先生。', grammarPoints: ['推测'] },
        { english: 'Tim\'s shirt is white.', chinese: '蒂姆的衬衫是白色的。', grammarPoints: ['所有格'] },
        { english: 'Here you are.', chinese: '给你。', grammarPoints: ['日常用语'] },
        { english: 'Catch!', chinese: '接着！', grammarPoints: ['日常用语'] },
      ],
      text: {
        title: 'Is this your shirt?',
        paragraphs: [
          { speaker: 'A', content: 'Whose shirt is that?' },
          { speaker: 'B', content: 'Is this your shirt, Dave?' },
          { speaker: 'C', content: 'No, sir.' },
          { speaker: 'C', content: 'It is not my shirt.' },
          { speaker: 'C', content: 'This is my shirt.' },
          { speaker: 'C', content: 'My shirt is blue.' },
          { speaker: 'B', content: 'Is this shirt Tim\'s?' },
          { speaker: 'B', content: 'Perhaps it is, sir.' },
          { speaker: 'B', content: 'Tim\'s shirt is white.' },
          { speaker: 'B', content: 'Tim!' },
          { speaker: 'D', content: 'Yes, sir?' },
          { speaker: 'B', content: 'Is this your shirt?' },
          { speaker: 'D', content: 'Yes, sir.' },
          { speaker: 'B', content: 'Here you are.' },
          { speaker: 'B', content: 'Catch!' },
          { speaker: 'D', content: 'Thank you, sir.' },
        ],
        translation: ['那是谁的衬衫？', '戴夫，这是你的衬衫吗？', '不，先生。', '这不是我的衬衫。', '这是我的衬衫。', '我的衬衫是蓝色的。', '这件衬衫是蒂姆的吗？', '也许是，先生。', '蒂姆的衬衫是白色的。', '蒂姆！', '什么事，先生？', '这是你的衬衫吗？', '是的，先生。', '给你。', '接着！', '谢谢您，先生。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Whose shirt is that? 的意思是？', options: ['那是谁的衬衫？', '这是谁的衬衫？', '那是你的衬衫吗？', '这是你的衬衫吗？'] }, answer: '那是谁的衬衫？', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：This is my shirt.', sentence: 'This is my shirt.' }, answer: 'This is my shirt.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：我的衬衫是蓝色的。', sentence: 'My shirt is blue.' }, answer: 'My shirt is blue.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：shirt', word: 'shirt', hint: '/ʃɜːt/' }, answer: 'shirt', score: 10 },
      ],
    },
  },
  // ========== Lesson 12: Whose is this...? ==========
  {
    id: 12,
    title: 'Lesson 12: Whose is this...?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'his', phonetic: '/hɪz/', meaning: '他的', examples: ['This is his book.', 'His shirt is white.'] },
        { word: 'her', phonetic: '/hɜː/', meaning: '她的', examples: ['This is her dress.', 'Her dress is red.'] },
        { word: 'my', phonetic: '/maɪ/', meaning: '我的', examples: ['This is my book.', 'My shirt is blue.'] },
        { word: 'your', phonetic: '/jɔː/', meaning: '你的', examples: ['This is your pen.', 'Your book is here.'] },
        { word: 'tie', phonetic: '/taɪ/', meaning: '领带', examples: ['This is his tie.', 'His tie is red.'] },
        { word: 'blouse', phonetic: '/blaʊz/', meaning: '女衬衫', examples: ['This is her blouse.', 'Her blouse is white.'] },
        { word: 'suit', phonetic: '/suːt/', meaning: '一套衣服', examples: ['This is his suit.', 'His suit is black.'] },
        { word: 'skirt', phonetic: '/skɜːt/', meaning: '裙子', examples: ['This is her skirt.', 'Her skirt is blue.'] },
      ],
      sentences: [
        { english: 'Whose is this pen?', chinese: '这枝钢笔是谁的？', grammarPoints: ['特殊疑问句', '物主代词'] },
        { english: 'This is my pen.', chinese: '这是我的钢笔。', grammarPoints: ['回答', '物主代词'] },
        { english: 'Whose is this tie?', chinese: '这条领带是谁的？', grammarPoints: ['特殊疑问句', '物主代词'] },
        { english: 'This is his tie.', chinese: '这是他的领带。', grammarPoints: ['回答', '物主代词'] },
        { english: 'Whose is this blouse?', chinese: '这件女衬衫是谁的？', grammarPoints: ['特殊疑问句', '物主代词'] },
        { english: 'This is her blouse.', chinese: '这是她的女衬衫。', grammarPoints: ['回答', '物主代词'] },
      ],
      text: {
        title: 'Whose is this...?',
        paragraphs: [
          { speaker: 'A', content: 'Whose is this pen?' },
          { speaker: 'B', content: 'This is my pen.' },
          { speaker: 'A', content: 'Whose is this tie?' },
          { speaker: 'B', content: 'This is his tie.' },
          { speaker: 'A', content: 'Whose is this blouse?' },
          { speaker: 'B', content: 'This is her blouse.' },
        ],
        translation: ['这枝钢笔是谁的？', '这是我的钢笔。', '这条领带是谁的？', '这是他的领带。', '这件女衬衫是谁的？', '这是她的女衬衫。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'This is his tie. 的意思是？', options: ['这是他的领带', '这是她的领带', '这是我的领带', '这是你的领带'] }, answer: '这是他的领带', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Whose is this?', sentence: 'Whose is this?' }, answer: 'Whose is this?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：这是她的裙子。', sentence: 'This is her skirt.' }, answer: 'This is her skirt.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：tie', word: 'tie', hint: '/taɪ/' }, answer: 'tie', score: 10 },
      ],
    },
  },
  // ========== Lesson 13: A new dress ==========
  {
    id: 13,
    title: 'Lesson 13: A new dress',
    type: 'new',
    grammar: '颜色形容词',
    content: {
      vocabulary: [
        { word: 'a', phonetic: '/ə/', meaning: '一个', examples: ['a dress', 'a book'] },
        { word: 'new', phonetic: '/njuː/', meaning: '新的', examples: ['a new dress', 'new shoes'] },
        { word: 'dress', phonetic: '/dres/', meaning: '连衣裙', examples: ['a new dress', 'her dress'] },
        { word: 'red', phonetic: '/red/', meaning: '红色的', examples: ['red dress', 'red apple'] },
        { word: 'colour', phonetic: '/ˈkʌlə/', meaning: '颜色', examples: ['What colour?', 'red colour'] },
        { word: 'green', phonetic: '/ɡriːn/', meaning: '绿色的', examples: ['green dress', 'green tree'] },
        { word: 'yellow', phonetic: '/ˈjeləʊ/', meaning: '黄色的', examples: ['yellow dress', 'yellow banana'] },
        { word: 'blue', phonetic: '/bluː/', meaning: '蓝色的', examples: ['blue dress', 'blue sky'] },
        { word: 'white', phonetic: '/waɪt/', meaning: '白色的', examples: ['white dress', 'white snow'] },
        { word: 'black', phonetic: '/blæk/', meaning: '黑色的', examples: ['black dress', 'black cat'] },
        { word: 'orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙色的', examples: ['orange dress', 'orange fruit'] },
      ],
      sentences: [
        { english: 'Look at my new dress.', chinese: '看我的新连衣裙。', grammarPoints: ['祈使句', '物主代词'] },
        { english: 'What colour is it?', chinese: '它是什么颜色的？', grammarPoints: ['特殊疑问句', '颜色'] },
        { english: "It's green.", chinese: '它是绿色的。', grammarPoints: ['回答颜色'] },
        { english: 'Come upstairs and see it.', chinese: '到楼上来看看吧。', grammarPoints: ['祈使句'] },
        { english: 'Thank you.', chinese: '谢谢。', grammarPoints: ['感谢'] },
        { english: 'Look! Here it is!', chinese: '瞧！就是这件。', grammarPoints: ['日常用语'] },
        { english: "That's a nice dress.", chinese: '这件连衣裙真好。', grammarPoints: ['赞美'] },
        { english: 'It is very smart.', chinese: '真漂亮。', grammarPoints: ['赞美'] },
        { english: 'My hat is new, too.', chinese: '我的帽子也是新的。', grammarPoints: ['too的用法'] },
        { english: 'What colour is your hat?', chinese: '你的帽子是什么颜色的？', grammarPoints: ['特殊疑问句', '颜色'] },
        { english: "It's the same colour.", chinese: '一样的颜色。', grammarPoints: ['相同颜色'] },
        { english: "It's green, too.", chinese: '也是绿色的。', grammarPoints: ['too的用法'] },
      ],
      text: {
        title: 'A new dress',
        paragraphs: [
          { speaker: 'A', content: 'Look at my new dress.' },
          { speaker: 'B', content: 'What colour is it?' },
          { speaker: 'A', content: "It's green." },
          { speaker: 'A', content: 'Come upstairs and see it.' },
          { speaker: 'B', content: 'Thank you.' },
          { speaker: 'A', content: 'Look! Here it is!' },
          { speaker: 'B', content: "That's a nice dress." },
          { speaker: 'B', content: 'It is very smart.' },
          { speaker: 'A', content: 'My hat is new, too.' },
          { speaker: 'B', content: 'What colour is your hat?' },
          { speaker: 'A', content: "It's the same colour." },
          { speaker: 'A', content: "It's green, too." },
        ],
        translation: ['看我的新连衣裙。', '它是什么颜色的？', '它是绿色的。', '到楼上来看看吧。', '谢谢。', '瞧！就是这件。', '这件连衣裙真好。', '真漂亮。', '我的帽子也是新的。', '你的帽子是什么颜色的？', '一样的颜色。', '也是绿色的。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'What colour is it? 的意思是？', options: ['它是什么颜色的？', '它是谁的？', '它是什么？', '它在哪里？'] }, answer: '它是什么颜色的？', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Look at my new dress.', sentence: 'Look at my new dress.' }, answer: 'Look at my new dress.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：这件连衣裙真好。', sentence: "That's a nice dress." }, answer: "That's a nice dress.", score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：colour', word: 'colour', hint: '/ˈkʌlə/' }, answer: 'colour', score: 10 },
      ],
    },
  },
  // ========== Lesson 14: What colour is your...? ==========
  {
    id: 14,
    title: 'Lesson 14: What colour is your...?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'grey', phonetic: '/ɡreɪ/', meaning: '灰色的', examples: ['grey suit', 'grey sky'] },
        { word: 'brown', phonetic: '/braʊn/', meaning: '棕色的', examples: ['brown coat', 'brown hair'] },
        { word: 'black', phonetic: '/blæk/', meaning: '黑色的', examples: ['black shoes', 'black bag'] },
        { word: 'blue', phonetic: '/bluː/', meaning: '蓝色的', examples: ['blue shirt', 'blue jeans'] },
        { word: 'yellow', phonetic: '/ˈjeləʊ/', meaning: '黄色的', examples: ['yellow hat', 'yellow pencil'] },
        { word: 'orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙色的', examples: ['orange dress', 'orange juice'] },
        { word: 'pink', phonetic: '/pɪŋk/', meaning: '粉色的', examples: ['pink skirt', 'pink flower'] },
        { word: 'purple', phonetic: '/ˈpɜːpl/', meaning: '紫色的', examples: ['purple blouse', 'purple flower'] },
      ],
      sentences: [
        { english: 'What colour is your shirt?', chinese: '你的衬衫是什么颜色的？', grammarPoints: ['特殊疑问句', '颜色'] },
        { english: "It's blue.", chinese: '它是蓝色的。', grammarPoints: ['回答颜色'] },
        { english: 'What colour is your coat?', chinese: '你的大衣是什么颜色的？', grammarPoints: ['特殊疑问句', '颜色'] },
        { english: "It's grey.", chinese: '它是灰色的。', grammarPoints: ['回答颜色'] },
      ],
      text: {
        title: 'What colour is your...?',
        paragraphs: [
          { speaker: 'A', content: 'What colour is your shirt?' },
          { speaker: 'B', content: "It's blue." },
          { speaker: 'A', content: 'What colour is your coat?' },
          { speaker: 'B', content: "It's grey." },
          { speaker: 'A', content: 'What colour is your dress?' },
          { speaker: 'B', content: "It's pink." },
        ],
        translation: ['你的衬衫是什么颜色的？', '它是蓝色的。', '你的大衣是什么颜色的？', '它是灰色的。', '你的连衣裙是什么颜色的？', '它是粉色的。'],
      },
      exercises: [
        { type: 'listening', content: { question: "It's grey. 的意思是？", options: ['它是灰色的', '它是绿色的', '它是蓝色的', '它是红色的'] }, answer: '它是灰色的', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What colour is your shirt?', sentence: 'What colour is your shirt?' }, answer: 'What colour is your shirt?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：你的连衣裙是什么颜色的？', sentence: 'What colour is your dress?' }, answer: 'What colour is your dress?', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：grey', word: 'grey', hint: '/ɡreɪ/' }, answer: 'grey', score: 10 },
      ],
    },
  },
  // ========== Lesson 15: Your passport, please ==========
  {
    id: 15,
    title: 'Lesson 15: Your passport, please',
    type: 'new',
    grammar: '请求与提供',
    content: {
      vocabulary: [
        { word: 'customs', phonetic: '/ˈkʌstəmz/', meaning: '海关', examples: ['customs officer', 'passport control'] },
        { word: 'officer', phonetic: '/ˈɒfɪsə/', meaning: '官员', examples: ['customs officer', 'police officer'] },
        { word: 'girl', phonetic: '/ɡɜːl/', meaning: '女孩', examples: ['a nice girl', 'That girl is beautiful.'] },
        { word: 'Danish', phonetic: '/ˈdeɪnɪʃ/', meaning: '丹麦的', examples: ['She is Danish.', 'Danish food.'] },
        { word: 'friend', phonetic: '/frend/', meaning: '朋友', examples: ['my friend', 'good friend'] },
        { word: 'Norwegian', phonetic: '/nɔːˈwiːdʒən/', meaning: '挪威的', examples: ['He is Norwegian.', 'Norwegian fjords.'] },
        { word: 'passport', phonetic: '/ˈpɑːspɔːt/', meaning: '护照', examples: ['your passport', 'show your passport'] },
        { word: 'brown', phonetic: '/braʊn/', meaning: '棕色的', examples: ['brown hair', 'brown eyes'] },
        { word: 'tourist', phonetic: '/ˈtʊərɪst/', meaning: '游客', examples: ['a tourist', 'tourist guide'] },
        { word: 'Russian', phonetic: '/ˈrʌʃən/', meaning: '俄罗斯的', examples: ['He is Russian.', 'Russian food.'] },
        { word: 'Dutch', phonetic: '/dʌtʃ/', meaning: '荷兰的', examples: ['She is Dutch.', 'Dutch cheese.'] },
        { word: 'these', phonetic: '/ðiːz/', meaning: '这些', examples: ['These are my books.', 'These apples are red.'] },
      ],
      sentences: [
        { english: 'Your passports, please.', chinese: '请出示你们的护照。', grammarPoints: ['请求'] },
        { english: 'Here they are.', chinese: '给你。', grammarPoints: ['提供'] },
        { english: 'Are you Swedish?', chinese: '你们是瑞典人吗？', grammarPoints: ['一般疑问句', '国籍'] },
        { english: 'No, we are not.', chinese: '不，我们不是。', grammarPoints: ['否定回答'] },
        { english: 'We are Danish.', chinese: '我们是丹麦人。', grammarPoints: ['回答国籍'] },
        { english: 'Are your friends Danish, too?', chinese: '你们的朋友也是丹麦人吗？', grammarPoints: ['一般疑问句'] },
        { english: 'No, they are not.', chinese: '不，他们不是。', grammarPoints: ['否定回答'] },
        { english: 'They are Norwegian.', chinese: '他们是挪威人。', grammarPoints: ['回答国籍'] },
        { english: 'Your passports, please.', chinese: '请出示你们的护照。', grammarPoints: ['请求'] },
        { english: 'Here you are.', chinese: '给你。', grammarPoints: ['提供'] },
        { english: 'Are you tourists?', chinese: '你们是游客吗？', grammarPoints: ['一般疑问句'] },
        { english: 'Yes, we are.', chinese: '是的，我们是。', grammarPoints: ['肯定回答'] },
        { english: 'Are your friends tourists too?', chinese: '你们的朋友也是游客吗？', grammarPoints: ['一般疑问句'] },
        { english: 'Yes, they are.', chinese: '是的，他们是。', grammarPoints: ['肯定回答'] },
        { english: 'That is fine.', chinese: '没问题。', grammarPoints: ['日常用语'] },
        { english: 'Thank you very much.', chinese: '非常感谢。', grammarPoints: ['感谢'] },
      ],
      text: {
        title: 'Your passport, please',
        paragraphs: [
          { speaker: 'Customs officer', content: 'Your passports, please.' },
          { speaker: 'Man', content: 'Here they are.' },
          { speaker: 'Customs officer', content: 'Are you Swedish?' },
          { speaker: 'Man', content: 'No, we are not.' },
          { speaker: 'Man', content: 'We are Danish.' },
          { speaker: 'Customs officer', content: 'Are your friends Danish, too?' },
          { speaker: 'Man', content: 'No, they are not.' },
          { speaker: 'Man', content: 'They are Norwegian.' },
          { speaker: 'Customs officer', content: 'Your passports, please.' },
          { speaker: 'Woman', content: 'Here you are.' },
          { speaker: 'Customs officer', content: 'Are you tourists?' },
          { speaker: 'Woman', content: 'Yes, we are.' },
          { speaker: 'Customs officer', content: 'Are your friends tourists too?' },
          { speaker: 'Woman', content: 'Yes, they are.' },
          { speaker: 'Customs officer', content: 'That is fine.' },
          { speaker: 'Customs officer', content: 'Thank you very much.' },
        ],
        translation: ['请出示你们的护照。', '给你。', '你们是瑞典人吗？', '不，我们不是。', '我们是丹麦人。', '你们的朋友也是丹麦人吗？', '不，他们不是。', '他们是挪威人。', '请出示你们的护照。', '给你。', '你们是游客吗？', '是的，我们是。', '你们的朋友也是游客吗？', '是的，他们是。', '没问题。', '非常感谢。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'Your passport, please. 的意思是？', options: ['请出示你的护照。', '这是你的护照。', '你的护照在哪里？', '你的护照是什么颜色的？'] }, answer: '请出示你的护照。', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Here you are.', sentence: 'Here you are.' }, answer: 'Here you are.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：他们是挪威人。', sentence: 'They are Norwegian.' }, answer: 'They are Norwegian.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：passport', word: 'passport', hint: '/ˈpɑːspɔːt/' }, answer: 'passport', score: 10 },
      ],
    },
  },
  // ========== Lesson 16: Are you...? ==========
  {
    id: 16,
    title: 'Lesson 16: Are you...?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'Swedish', phonetic: '/ˈswiːdɪʃ/', meaning: '瑞典的', examples: ['Swedish food', 'Swedish people'] },
        { word: 'English', phonetic: '/ˈɪŋɡlɪʃ/', meaning: '英国的', examples: ['English food', 'English people'] },
        { word: 'American', phonetic: '/əˈmerɪkən/', meaning: '美国的', examples: ['American food', 'American people'] },
        { word: 'Italian', phonetic: '/ɪˈtæliən/', meaning: '意大利的', examples: ['Italian food', 'Italian people'] },
        { word: 'Greek', phonetic: '/ɡriːk/', meaning: '希腊的', examples: ['Greek food', 'Greek people'] },
        { word: 'French', phonetic: '/frentʃ/', meaning: '法国的', examples: ['French food', 'French people'] },
        { word: 'German', phonetic: '/ˈdʒɜːmən/', meaning: '德国的', examples: ['German food', 'German people'] },
        { word: 'Japanese', phonetic: '/ˌdʒæpəˈniːz/', meaning: '日本的', examples: ['Japanese food', 'Japanese people'] },
      ],
      sentences: [
        { english: 'Are you Swedish?', chinese: '你是瑞典人吗？', grammarPoints: ['一般疑问句', '国籍'] },
        { english: 'Yes, I am.', chinese: '是的，我是。', grammarPoints: ['肯定回答'] },
        { english: 'Are you English?', chinese: '你是英国人吗？', grammarPoints: ['一般疑问句', '国籍'] },
        { english: 'No, I am not.', chinese: '不，我不是。', grammarPoints: ['否定回答'] },
      ],
      text: {
        title: 'Are you...?',
        paragraphs: [
          { speaker: 'A', content: 'Are you Swedish?' },
          { speaker: 'B', content: 'Yes, I am.' },
          { speaker: 'A', content: 'Are you English?' },
          { speaker: 'B', content: 'No, I am not.' },
          { speaker: 'A', content: 'What nationality are you?' },
          { speaker: 'B', content: 'I am American.' },
        ],
        translation: ['你是瑞典人吗？', '是的，我是。', '你是英国人吗？', '不，我不是。', '你是哪国人？', '我是美国人。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'I am American. 的意思是？', options: ['我是美国人', '我是英国人', '我是瑞典人', '我是意大利人'] }, answer: '我是美国人', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Are you Italian?', sentence: 'Are you Italian?' }, answer: 'Are you Italian?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：你是哪国人？', sentence: 'What nationality are you?' }, answer: 'What nationality are you?', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：English', word: 'English', hint: '/ˈɪŋɡlɪʃ/' }, answer: 'English', score: 10 },
      ],
    },
  },
  // ========== Lesson 17: How do you do? ==========
  {
    id: 17,
    title: 'Lesson 17: How do you do?',
    type: 'new',
    grammar: '正式问候',
    content: {
      vocabulary: [
        { word: 'employee', phonetic: '/ɪmˈplɔɪiː/', meaning: '雇员', examples: ['office employee', 'new employee'] },
        { word: 'hard-working', phonetic: '/ˌhɑːdˈwɜːkɪŋ/', meaning: '勤奋的', examples: ['hard-working employee', 'hard-working student'] },
        { word: 'sales rep', phonetic: '/seɪlz rep/', meaning: '推销员', examples: ['a sales rep', 'sales representative'] },
        { word: 'man', phonetic: '/mæn/', meaning: '男人', examples: ['a tall man', 'the man is tall'] },
        { word: 'office', phonetic: '/ˈɒfɪs/', meaning: '办公室', examples: ['office worker', 'office building'] },
        { word: 'assistant', phonetic: '/əˈsɪstənt/', meaning: '助手', examples: ['office assistant', 'personal assistant'] },
        { word: 'woman', phonetic: '/ˈwʊmən/', meaning: '女人', examples: ['a beautiful woman', 'the woman is nice'] },
        { word: 'these', phonetic: '/ðiːz/', meaning: '这些', examples: ['these employees', 'these books'] },
        { word: 'work', phonetic: '/wɜːk/', meaning: '工作', examples: ['go to work', 'work hard'] },
        { word: 'at', phonetic: '/æt/', meaning: '在', examples: ['at work', 'at home'] },
      ],
      sentences: [
        { english: 'These are our employees.', chinese: '这些是我们的雇员。', grammarPoints: ['介绍'] },
        { english: 'Who is this young man?', chinese: '这个年轻人是谁？', grammarPoints: ['特殊疑问句'] },
        { english: 'This is Jim.', chinese: '这位是吉姆。', grammarPoints: ['介绍'] },
        { english: 'He is our office assistant.', chinese: '他是我们办公室的助理。', grammarPoints: ['介绍职业'] },
        { english: 'How do you do?', chinese: '你好。', grammarPoints: ['正式问候'] },
        { english: 'How do you do?', chinese: '你好。', grammarPoints: ['回应正式问候'] },
        { english: 'And this is Sophie.', chinese: '这位是索菲娅。', grammarPoints: ['介绍'] },
        { english: 'She is a new student.', chinese: '她是个新学生。', grammarPoints: ['介绍'] },
        { english: 'She is French.', chinese: '她是法国人。', grammarPoints: ['国籍'] },
        { english: 'Nice to meet you.', chinese: '很高兴见到你。', grammarPoints: ['问候'] },
        { english: 'Nice to meet you, too.', chinese: '我见到你也很高兴。', grammarPoints: ['回应问候'] },
        { english: 'These women are very hard-working.', chinese: '这些女雇员很勤奋。', grammarPoints: ['描述'] },
      ],
      text: {
        title: 'How do you do?',
        paragraphs: [
          { speaker: 'Mr. Jackson', content: 'Come and meet our employees, Mr. Richards.' },
          { speaker: 'Mr. Richards', content: 'Thank you, Mr. Jackson.' },
          { speaker: 'Mr. Jackson', content: 'This is Nicola Grey, and this is Claire Taylor.' },
          { speaker: 'Mr. Richards', content: 'How do you do?' },
          { speaker: 'Mr. Richards', content: 'Those women are very hard-working.' },
          { speaker: 'Mr. Jackson', content: 'What are their jobs?' },
          { speaker: 'Mr. Richards', content: "They're keyboard operators." },
          { speaker: 'Mr. Jackson', content: 'This is Michael Baker, and this is Jeremy Short.' },
          { speaker: 'Mr. Richards', content: 'How do you do?' },
          { speaker: 'Mr. Richards', content: 'They are not very busy!' },
          { speaker: 'Mr. Richards', content: "What are their jobs?" },
          { speaker: 'Mr. Jackson', content: "They're sales reps." },
          { speaker: 'Mr. Richards', content: 'They are very lazy!' },
          { speaker: 'Mr. Jackson', content: 'Who is this young man?' },
          { speaker: 'Mr. Richards', content: 'This is Jim.' },
          { speaker: 'Mr. Richards', content: 'He is our office assistant.' },
        ],
        translation: ['来见见我们的雇员，理查兹先生。', '谢谢，杰克逊先生。', '这位是尼古拉·格雷，这位是克莱尔·泰勒。', '你好。', '那些女雇员很勤奋。', '她们是做什么工作的？', '她们是电脑录入员。', '这位是迈克尔·贝克，这位是杰里米·肖特。', '你好。', '他们不是很忙！', '他们是做什么工作的？', '他们是推销员。', '他们非常懒！', '这个年轻人是谁？', '这位是吉姆。', '他是我们办公室的助理。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'How do you do? 的意思是？', options: ['你好。', '你好吗？', '你做什么工作？', '你是谁？'] }, answer: '你好。', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Come and meet our employees.', sentence: 'Come and meet our employees.' }, answer: 'Come and meet our employees.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：他是我们办公室的助理。', sentence: 'He is our office assistant.' }, answer: 'He is our office assistant.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：employee', word: 'employee', hint: '/ɪmˈplɔɪiː/' }, answer: 'employee', score: 10 },
      ],
    },
  },
  // ========== Lesson 18: What are their jobs? ==========
  {
    id: 18,
    title: 'Lesson 18: What are their jobs?',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'jobs', phonetic: '/dʒɒbz/', meaning: '工作（复数）', examples: ['What are their jobs?', 'different jobs'] },
        { word: 'engineer', phonetic: '/ˌendʒɪˈnɪə/', meaning: '工程师', examples: ['He is an engineer.', 'engineer job'] },
        { word: 'mechanic', phonetic: '/mɪˈkænɪk/', meaning: '机械师', examples: ['He is a mechanic.', 'mechanic job'] },
        { word: 'hairdresser', phonetic: '/ˈheədresə/', meaning: '理发师', examples: ['He is a hairdresser.', 'hairdresser job'] },
        { word: 'housewife', phonetic: '/ˈhaʊswaɪf/', meaning: '家庭主妇', examples: ['She is a housewife.', 'housewife job'] },
        { word: 'milkman', phonetic: '/ˈmɪlkmən/', meaning: '送奶工', examples: ['He is a milkman.', 'milkman job'] },
        { word: 'policewoman', phonetic: '/pəˈliːswʊmən/', meaning: '女警察', examples: ['She is a policewoman.', 'policewoman job'] },
        { word: 'taxi driver', phonetic: '/ˈtæksi ˈdraɪvə/', meaning: '出租车司机', examples: ['He is a taxi driver.', 'taxi driver job'] },
      ],
      sentences: [
        { english: 'What are their jobs?', chinese: '他们是做什么工作的？', grammarPoints: ['特殊疑问句', '职业'] },
        { english: 'They are engineers.', chinese: '他们是工程师。', grammarPoints: ['回答职业'] },
        { english: 'What are their jobs?', chinese: '他们是做什么工作的？', grammarPoints: ['特殊疑问句', '职业'] },
        { english: 'They are mechanics.', chinese: '他们是机械师。', grammarPoints: ['回答职业'] },
      ],
      text: {
        title: 'What are their jobs?',
        paragraphs: [
          { speaker: 'A', content: 'What are their jobs?' },
          { speaker: 'B', content: 'They are engineers.' },
          { speaker: 'A', content: 'What are their jobs?' },
          { speaker: 'B', content: 'They are mechanics.' },
          { speaker: 'A', content: 'What are their jobs?' },
          { speaker: 'B', content: 'They are taxi drivers.' },
        ],
        translation: ['他们是做什么工作的？', '他们是工程师。', '他们是做什么工作的？', '他们是机械师。', '他们是做什么工作的？', '他们是出租车司机。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'They are mechanics. 的意思是？', options: ['他们是机械师', '他们是工程师', '他们是理发师', '他们是出租车司机'] }, answer: '他们是机械师', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What are their jobs?', sentence: 'What are their jobs?' }, answer: 'What are their jobs?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：他们是出租车司机。', sentence: 'They are taxi drivers.' }, answer: 'They are taxi drivers.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：engineer', word: 'engineer', hint: '/ˌendʒɪˈnɪə/' }, answer: 'engineer', score: 10 },
      ],
    },
  },
  // ========== Lesson 19: Tired and thirsty ==========
  {
    id: 19,
    title: 'Lesson 19: Tired and thirsty',
    type: 'new',
    grammar: '形容词描述',
    content: {
      vocabulary: [
        { word: 'matter', phonetic: '/ˈmætə/', meaning: '事情', examples: ['What is the matter?', 'It does not matter.'] },
        { word: 'children', phonetic: '/ˈtʃɪldrən/', meaning: '孩子们', examples: ['The children are tired.', 'My children are happy.'] },
        { word: 'tired', phonetic: '/ˈtaɪəd/', meaning: '累的', examples: ['I am tired.', 'He is tired.'] },
        { word: 'thirsty', phonetic: '/ˈθɜːsti/', meaning: '渴的', examples: ['I am thirsty.', 'She is thirsty.'] },
        { word: 'boy', phonetic: '/bɔɪ/', meaning: '男孩', examples: ['The boy is tired.', 'A little boy.'] },
        { word: 'girl', phonetic: '/ɡɜːl/', meaning: '女孩', examples: ['The girl is thirsty.', 'A little girl.'] },
        { word: 'sit down', phonetic: '/sɪt daʊn/', meaning: '坐下', examples: ['Please sit down.', 'Sit down, please.'] },
        { word: 'right', phonetic: '/raɪt/', meaning: '好的', examples: ['All right.', 'That is right.'] },
        { word: 'father', phonetic: '/ˈfɑːðə/', meaning: '父亲', examples: ['My father is tired.', 'His father is a doctor.'] },
        { word: 'now', phonetic: '/naʊ/', meaning: '现在', examples: ['Now, sit down.', 'Come now.'] },
        { word: 'clean', phonetic: '/kliːn/', meaning: '干净的', examples: ['The cup is clean.', 'Clean the room.'] },
        { word: 'glass', phonetic: '/ɡlɑːs/', meaning: '杯子', examples: ['a glass of water', 'a clean glass'] },
        { word: 'heavy', phonetic: '/ˈhevi/', meaning: '重的', examples: ['The box is heavy.', 'This bag is heavy.'] },
        { word: 'light', phonetic: '/laɪt/', meaning: '轻的', examples: ['The box is light.', 'This bag is light.'] },
      ],
      sentences: [
        { english: 'What is the matter, children?', chinese: '孩子们，你们怎么了？', grammarPoints: ['关心询问'] },
        { english: 'We are tired and thirsty, Mum.', chinese: '妈妈，我们又累又渴。', grammarPoints: ['描述状态'] },
        { english: 'Sit down here.', chinese: '坐这儿吧。', grammarPoints: ['祈使句'] },
        { english: 'Are you all right now?', chinese: '现在好些了吗？', grammarPoints: ['关心询问'] },
        { english: 'No, we are not.', chinese: '不，还没有。', grammarPoints: ['否定回答'] },
        { english: 'Look! There is an ice cream man.', chinese: '看！有个卖冰淇淋的。', grammarPoints: ['发现'] },
        { english: 'Two ice creams, please.', chinese: '请拿两份冰淇淋。', grammarPoints: ['请求'] },
        { english: 'Here you are, children.', chinese: '给你们，孩子们。', grammarPoints: ['提供'] },
        { english: 'Thanks, Mum.', chinese: '谢谢，妈妈。', grammarPoints: ['感谢'] },
        { english: 'These ice creams are nice.', chinese: '这些冰淇淋真好吃。', grammarPoints: ['赞美'] },
        { english: 'Are you all right now?', chinese: '现在好了吗？', grammarPoints: ['关心询问'] },
        { english: 'Yes, we are, thank you.', chinese: '是的，好了，谢谢。', grammarPoints: ['肯定回答', '感谢'] },
      ],
      text: {
        title: 'Tired and thirsty',
        paragraphs: [
          { speaker: 'Mother', content: 'What is the matter, children?' },
          { speaker: 'Children', content: 'We are tired and thirsty, Mum.' },
          { speaker: 'Mother', content: 'Sit down here.' },
          { speaker: 'Mother', content: 'Are you all right now?' },
          { speaker: 'Children', content: 'No, we are not.' },
          { speaker: 'Mother', content: 'Look! There is an ice cream man.' },
          { speaker: 'Mother', content: 'Two ice creams, please.' },
          { speaker: 'Ice cream man', content: 'Here you are, children.' },
          { speaker: 'Children', content: 'Thanks, Mum.' },
          { speaker: 'Children', content: 'These ice creams are nice.' },
          { speaker: 'Mother', content: 'Are you all right now?' },
          { speaker: 'Children', content: 'Yes, we are, thank you.' },
        ],
        translation: ['孩子们，你们怎么了？', '妈妈，我们又累又渴。', '坐这儿吧。', '现在好些了吗？', '不，还没有。', '看！有个卖冰淇淋的。', '请拿两份冰淇淋。', '给你们，孩子们。', '谢谢，妈妈。', '这些冰淇淋真好吃。', '现在好了吗？', '是的，好了，谢谢。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'We are tired and thirsty. 的意思是？', options: ['我们又累又渴', '我们又饿又累', '我们又渴又饿', '我们又困又累'] }, answer: '我们又累又渴', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：What is the matter?', sentence: 'What is the matter?' }, answer: 'What is the matter?', score: 10 },
        { type: 'writing', content: { instruction: '翻译：坐这儿吧。', sentence: 'Sit down here.' }, answer: 'Sit down here.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：tired', word: 'tired', hint: '/ˈtaɪəd/' }, answer: 'tired', score: 10 },
      ],
    },
  },
  // ========== Lesson 20: Look at... ==========
  {
    id: 20,
    title: 'Lesson 20: Look at...',
    type: 'review',
    grammar: '复习课',
    content: {
      vocabulary: [
        { word: 'full', phonetic: '/fʊl/', meaning: '满的', examples: ['The glass is full.', 'full of water'] },
        { word: 'empty', phonetic: '/ˈempti/', meaning: '空的', examples: ['The glass is empty.', 'empty box'] },
        { word: 'large', phonetic: '/lɑːdʒ/', meaning: '大的', examples: ['a large box', 'large house'] },
        { word: 'little', phonetic: '/ˈlɪtl/', meaning: '小的', examples: ['a little boy', 'little girl'] },
        { word: 'sharp', phonetic: '/ʃɑːp/', meaning: '锋利的', examples: ['sharp knife', 'sharp pencil'] },
        { word: 'blunt', phonetic: '/blʌnt/', meaning: '钝的', examples: ['blunt knife', 'blunt pencil'] },
        { word: 'big', phonetic: '/bɪɡ/', meaning: '大的', examples: ['big box', 'big house'] },
        { word: 'small', phonetic: '/smɔːl/', meaning: '小的', examples: ['small box', 'small house'] },
      ],
      sentences: [
        { english: 'Look at that glass.', chinese: '看那个杯子。', grammarPoints: ['祈使句'] },
        { english: 'It is full.', chinese: '它是满的。', grammarPoints: ['描述状态'] },
        { english: 'Look at that glass.', chinese: '看那个杯子。', grammarPoints: ['祈使句'] },
        { english: 'It is empty.', chinese: '它是空的。', grammarPoints: ['描述状态'] },
        { english: 'Look at that box.', chinese: '看那个盒子。', grammarPoints: ['祈使句'] },
        { english: 'It is large.', chinese: '它是大的。', grammarPoints: ['描述状态'] },
        { english: 'Look at that box.', chinese: '看那个盒子。', grammarPoints: ['祈使句'] },
        { english: 'It is little.', chinese: '它是小的。', grammarPoints: ['描述状态'] },
      ],
      text: {
        title: 'Look at...',
        paragraphs: [
          { speaker: 'A', content: 'Look at that glass.' },
          { speaker: 'B', content: 'It is full.' },
          { speaker: 'A', content: 'Look at that glass.' },
          { speaker: 'B', content: 'It is empty.' },
          { speaker: 'A', content: 'Look at that box.' },
          { speaker: 'B', content: 'It is large.' },
          { speaker: 'A', content: 'Look at that box.' },
          { speaker: 'B', content: 'It is little.' },
        ],
        translation: ['看那个杯子。', '它是满的。', '看那个杯子。', '它是空的。', '看那个盒子。', '它是大的。', '看那个盒子。', '它是小的。'],
      },
      exercises: [
        { type: 'listening', content: { question: 'It is empty. 的意思是？', options: ['它是空的', '它是满的', '它是大的', '它是小的'] }, answer: '它是空的', score: 10 },
        { type: 'speaking', content: { instruction: '跟读：Look at that glass.', sentence: 'Look at that glass.' }, answer: 'Look at that glass.', score: 10 },
        { type: 'writing', content: { instruction: '翻译：它是大的。', sentence: 'It is large.' }, answer: 'It is large.', score: 10 },
        { type: 'spelling', content: { instruction: '拼写单词：full', word: 'full', hint: '/fʊl/' }, answer: 'full', score: 10 },
      ],
    },
  },
];

export default realLessons;